import { TemplateComponent } from "@components/_template";
import AnimationBox from "@components/AnimationBox";
import { ShiftButton } from "@components/ShiftButton";
import { APP_NAME } from "@env";
import { useAppStore } from "@states/app";
import { cx } from "@utils/tools";
import Head from "next/head";
import Image from "next/image";

import styles from "./styles.module.scss";

export const HomeScreen: IComponent = () => {
  const { darkMode } = useAppStore();

  return (
    <div
      className={cx(
        styles.container,
        "dark:text-white p-40  relative h-screen"
      )}
    >
      <Head>
        <title>Substrate Frontend Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} relative z-20`}>
        <div className={styles.title}>
          <TemplateComponent
            text="Welcome to"
            color={darkMode === "dark" ? "white" : "black"}
          />
          <h1>{APP_NAME}</h1>
        </div>
        <ShiftButton route="/app" />
      </main>

      <footer className={`${styles.footer} sticky`}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>

      {darkMode === "dark" ? <AnimationBox /> : null}
    </div>
  );
};
